services:
    symfonyart_upload_handler.service.image_handler:
        class: SymfonyArt\UploadHandlerBundle\Service\ImageHandler
        arguments:
            - @liip_imagine.cache.manager
            - @liip_imagine.filter.manager